export const JOB_TITLES = [
  "Chief Executive or Managing Director",
  "Corporate General Manager",
  "Aquaculture Farmer",
  "Apiarist",
  "Dairy Cattle Farmer",
  "Goat Farmer",
  "Pig Farmer",
  "Poultry Farmer",
  "Flower Grower",
  "Sales and Marketing Manager",
  "Advertising Manager",
  "Corporate Services Manager",
  "Finance Manager",
  "Human Resource Manager",
  "Policy and Planning Manager",
  "Research and Development Manager",
  "Construction Project Manager",
  "Project Builder",
  "Engineering Manager",
  "Production Manager (Forestry)",
  "Production Manager (Manufacturing)",
  "Supply and Distribution Manager",
  "Procurement Manager",
  "Medical Administrator",
  "Medical Superintendent",
  "Nursing Clinical Director",
  "Primary Health Organisation Manager",
  "School Principal",
  "Faculty Head",
  "Chief Information Officer",
  "ICT Project Manager",
  "Arts Administrator or Manager",
  "Environmental Manager",
  "Laboratory Manager",
  "Quality Assurance Manager",
  "Regulatory Affairs Manager",
  "Hotel or Motel Manager",
  "Licensed Club Manager",
  "Retail Manager (General)",
  "Travel Agency Manager",
  "Fleet Manager",
  "Boarding Kennel or Cattery Operator",
  "Cinema or Theatre Manager",
  "Equipment Hire Manager",
  "Music Director",
  "Artistic Director",
  "Program Director (Television or Radio)",
  "Stage Manager",
  "Technical Director",
  "Video Producer",
  "Print Journalist",
  "Radio Journalist",
  "Technical Writer",
  "Television Journalist",
  "Accountant (General)",
  "Management Accountant",
  "Taxation Accountant",
  "Company Secretary",
  "External Auditor",
  "Internal Auditor",
  "Finance Broker",
  "Insurance Broker",
  "Financial Investment Adviser",
  "Human Resource Adviser",
  "Recruitment Consultant",
  "Workplace Relations Adviser",
  "Actuary",
  "Mathematician",
  "Data Analyst",
  "Data Scientist",
  "Statistician",
  "Land Economist",
  "Valuer",
  "Organisation and Methods Analyst",
  "Management Consultant",
  "Supply Chain Analyst",
  "Patents Examiner",
  "Advertising Specialist",
  "Marketing Specialist",
  "Content Creator (Marketing)",
  "ICT Account Manager",
  "ICT Business Development Manager",
  "ICT Sales Representative",
  "Public Relations Professional",
  "Sales Representative (Industrial Products)",
  "Sales Representative (Medical and Pharmaceutical Products)",
  "Aeroplane Pilot",
  "Flying Instructor",
  "Helicopter Pilot",
  "Ship's Engineer",
  "Architect",
  "Landscape Architect",
  "Surveyor",
  "Cartographer",
  "Other Spatial Scientist",
  "Jewellery Designer",
  "Illustrator",
  "Multimedia Designer",
  "Web Designer",
  "Interior Designer",
  "Urban and Regional Planner",
  "Chemical Engineer",
  "Materials Engineer",
  "Civil Engineer",
  "Geotechnical Engineer",
  "Quantity Surveyor",
  "Structural Engineer",
  "Transport Engineer",
  "Electrical Engineer",
  "Electronics Engineer",
  "Industrial Engineer",
  "Mechanical Engineer",
  "Production or Plant Engineer",
  "Mining Engineer (excluding Petroleum)",
  "Petroleum Engineer",
  "Aeronautical Engineer",
  "Agricultural Engineer",
  "Biomedical Engineer",
  "Engineering Technologist",
  "Environmental Engineer",
  "Naval Architect",
  "Marine Designer",
  "Agricultural Consultant",
  "Agricultural Research Scientist",
  "Agronomist",
  "Aquaculture or Fisheries Scientist",
  "Chemist",
  "Food Technologist",
  "Wine Maker",
  "Environmental Consultant",
  "Geologist",
  "Geophysicist",
  "Hydrogeologist",
  "Life Scientist (General)",
  "Biochemist",
  "Botanist",
  "Marine Biologist",
  "Entomologist",
  "Zoologist",
  "Respiratory Scientist",
  "Veterinarian",
  "Conservator",
  "Metallurgist",
  "Meteorologist",
  "Physicist",
  "Early Childhood (Pre-primary School) Teacher",
  "Primary School Teacher",
  "Middle School Teacher",
  "Intermediate School Teacher",
  "Secondary School Teacher",
  "Special Needs Teacher",
  "Teacher of the Hearing Impaired",
  "Teacher of the Sight Impaired",
  "University Lecturer",
  "Vocational Education Teacher",
  "Polytechnic Teacher",
  "Education Reviewer",
  "Music Teacher (Private Tuition)",
  "Dietitian",
  "Medical Diagnostic Radiographer",
  "Medical Radiation Therapist",
  "Nuclear Medicine Technologist",
  "Sonographer",
  "Occupational Health and Safety Adviser",
  "Optometrist",
  "Orthoptist",
  "Hospital Pharmacist",
  "Industrial Pharmacist",
  "Retail Pharmacist",
  "Orthotist or Prosthetist",
  "Traditional Chinese Medicine Practitioner",
  "Dental Specialist",
  "Dentist",
  "Occupational Therapist",
  "Physiotherapist",
  "Podiatrist",
  "Audiologist",
  "Speech Pathologist",
  "Speech Language Therapist",
  "General Practitioner",
  "Resident Medical Officer",
  "Anaesthetist",
  "Specialist Physician (General Medicine)",
  "Cardiologist",
  "Clinical Haematologist",
  "Medical Oncologist",
  "Endocrinologist",
  "Gastroenterologist",
  "Intensive Care Specialist",
  "Neurologist",
  "Paediatrician",
  "Renal Medicine Specialist",
  "Rheumatologist",
  "Thoracic Medicine Specialist",
  "Psychiatrist",
  "Surgeon (General)",
  "Cardiothoracic Surgeon",
  "Neurosurgeon",
  "Orthopaedic Surgeon",
  "Otorhinolaryngologist",
  "Paediatric Surgeon",
  "Plastic and Reconstructive Surgeon",
  "Urologist",
  "Vascular Surgeon",
  "Dermatologist",
  "Emergency Medicine Specialist",
  "Obstetrician and Gynaecologist",
  "Ophthalmologist",
  "Pathologist",
  "Diagnostic and Interventional Radiologist",
  "Radiation Oncologist",
  "Midwife",
  "Nurse Educator",
  "Nurse Researcher",
  "Nurse Practitioner",
  "Registered Nurse (Aged Care)",
  "Registered Nurse (Child and Family Health)",
  "Registered Nurse (Community Health)",
  "Registered Nurse (Critical Care and Emergency)",
  "Registered Nurse (Developmental Disability)",
  "Registered Nurse (Disability and Rehabilitation)",
  "Registered Nurse (Medical)",
  "Registered Nurse (Medical Practice)",
  "Registered Nurse (Mental Health)",
  "Registered Nurse (Perioperative)",
  "Registered Nurse (Surgical)",
  "Registered Nurse (Paediatrics)",
  "Software Engineer",
  "DevOps Engineer",
  "Business Analyst",
  "Database Administrator"
];

export const LOCATIONS = [
  "Sydney NSW",
  "Melbourne VIC",
  "Brisbane QLD",
  "Perth WA",
  "Adelaide SA",
  "Canberra ACT",
  "Hobart TAS",
  "Darwin NT",
  "Gold Coast QLD",
  "Newcastle NSW",
  "Wollongong NSW",
  "Geelong VIC",
  "Sunshine Coast QLD",
  "Townsville QLD",
  "Cairns QLD",
  "Toowoomba QLD",
  "Ballarat VIC",
  "Bendigo VIC",
  "Launceston TAS",
  "Mackay QLD",
  "Rockhampton QLD",
  "Bunbury WA",
  "Bundaberg QLD",
  "Hervey Bay QLD",
  "Wagga Wagga NSW",
  "Mildura VIC",
  "Shepparton VIC",
  "Port Macquarie NSW",
  "Gladstone QLD",
  "Tamworth NSW"
];
